# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9
      working_directory: /go/src/github.com/zhangmingkai4315/alertmanager-history
    steps:
      - checkout
      - run: go get github.com/mitchellh/gox
      - run: go get github.com/tcnksm/ghr
      - run: gox -output "tmp/alertmanager-history_{{.OS}}_{{.Arch}}"
      - run: sh save_artifact.sh
      - run: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r CIRCLE_PROJECT_REPONAME --replace `git describe --tags` dist/